name: Security

on:
  pull_request:
  push:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - run: uv sync --all-groups

      - run: uv run pip-audit